export * from './programa-academico.model';
export * from './asignatura.model';
export * from './grupo.model';
export * from './usuario.model';
export * from './perfil.model';
export * from './notificaciones.model';
export * from './notificaciones-por-usuario.model';
export * from './usuario-por-grupo.model';
export * from './credenciales.model';
